# Generated by Django 3.1.7 on 2021-04-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210404_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_first',
            field=models.BooleanField(default=0),
        ),
    ]
